import { MetadataRoute } from 'next'
import { allBlogIndexPosts } from './blog/blog-posts'
import { SITE_URL } from '@/lib/seo'

// Only canonical URLs belong here. Do not invent lastModified dates on each build.
const routes = [
  "/",
  "/about",
  "/apartment-chimney-sweep-seattle",
  "/blog",
  "/blog/fake-chimney-sweep-companies-seattle",
  "/certified-chimney-sweep",
  "/chimney-cap-installation",
  "/chimney-cleaning",
  "/chimney-cleaning-bellevue",
  "/chimney-cleaning-seattle",
  "/chimney-crown-repair",
  "/chimney-inspection",
  "/chimney-inspection-bellevue",
  "/chimney-liner-installation",
  "/chimney-repair-bellevue",
  "/chimney-repair-seattle",
  "/chimney-sweep-bellevue",
  "/chimney-sweep-bothell",
  "/chimney-sweep-everett",
  "/chimney-sweep-kenmore",
  "/chimney-sweep-kent",
  "/chimney-sweep-kirkland",
  "/chimney-sweep-lake-forest-park",
  "/chimney-sweep-mercer-island",
  "/chimney-sweep-near-me",
  "/chimney-sweep-newcastle",
  "/chimney-sweep-redmond",
  "/chimney-sweep-renton",
  "/chimney-sweep-sammamish",
  "/chimney-sweep-seattle",
  "/chimney-sweep-shoreline",
  "/chimney-sweep-woodinville",
  "/chimney-waterproofing",
  "/contact",
  "/creosote-removal",
  "/firebox-repair",
  "/fireplace-cleaning",
  "/fraud-check",
  "/locations",
  "/locations/arlington",
  "/locations/burien",
  "/locations/edmonds",
  "/locations/issaquah",
  "/locations/lake-stevens",
  "/locations/lynnwood",
  "/locations/marysville",
  "/locations/mountlake-terrace",
  "/locations/mukilteo",
  "/locations/snohomish",
  "/masonry-repair",
  "/privacy-policy",
  "/resources",
  "/resources/chimney-smells-smoky",
  "/resources/chimney-sweep-cost",
  "/resources/creosote-buildup-signs",
  "/resources/fireplace-not-drawing",
  "/resources/water-leaking-through-chimney",
  "/resources/white-stuff-on-chimney",
  "/services",
  "/smoky-fireplace-solutions",
  "/terms-of-service",
  "/troubleshooting-chimney",
  "/verify-contractor"
]

export default function sitemap(): MetadataRoute.Sitemap {
  const paths = new Set([...routes, ...allBlogIndexPosts.map(post => `/blog/${post.slug}`)])
  return [...paths].map(path => ({ url: new URL(path, SITE_URL).href }))
}
